config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get 'login', to: 'home#login'
  get 'logout', to: 'home#logout'
  post 'session', to: 'home#create_session'

  resources :categories, only: :show do
    resources :posts, except: :index
  end

  resources :categories, :posts do
    resources :comments, only: %i[create destroy]
  end

  resources :comments, only: %i[create destroy]

  get 'success', to: 'requests#success'

  namespace :admin do

    root 'categories#index'

    resources :categories
    resources :settings, only: %i[index update]
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @categories = Category.all.paginate(page: params[:page], per_page: 10)
  end

  def login
  end

  def create_session
    if params[:email].downcase == @settings.email.downcase && Digest::MD5.hexdigest(params[:password]) == @settings.password
      session[:admin] = 'true'
      redirect_to admin_root_path
    else
      redirect_to login_path, alert: 'Sorry, try again please'
    end
  end

  def logout
    session[:admin] = nil
    redirect_to root_path
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="container">
  <div class="wrapper">
    <div class="page-header">
      <h1>Another One Blog</h1>
      <h3>Blog about something interesting should be?</h3>
    </div>
    <div class="row">
      <% if @categories.present? %>
        <% @categories.each do |category| %>
          <div class="panel panel-success">
            <div class="panel-heading">      
              <h2 class="panel-title"><%=category.name %></h2>
            </div>
            <div class="panel-body">
              <h3 class="desc"><%=category.description %></h3>
              <%= link_to category_path(category), class: 'btn btn-info' do %>
                See Posts in Category
              <% end %>
            </div>
          </div>
        <% end %>
      <% else %>
        <h4>There are no Categories yet.</h4>
      <% end %>
    </div>
    <div class="container">
      <div class="row">
        <div class=".col-md-4"><%=will_paginate @categories, :renderer => BootstrapPagination::Rails %></div>
      </div>
    </div>
  </div>
</div>

app/views/home/login.html.erb
<div class="login-box">
  <div class="wrapper">
    <div class="container">
      <h1>Log In</h1>
      <%= form_tag(session_path) do %>
        <p class="label">Email:</p>
        <p><%= email_field_tag :email %></p>
        <p class="label">Password:</p>
        <p><%= password_field_tag :password %></p>
        <p class="submit"><%= submit_tag 'Login' %></p>
      <% end %>
    </div>
  </div>
</div>