config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get 'login', to: 'home#login'
  get 'logout', to: 'home#logout'
  post 'session', to: 'home#create_session'

  resources :categories, only: :show do
    resources :posts, except: :index
  end

  resources :categories, :posts do
    resources :comments, only: %i[create destroy]
  end

  resources :comments, only: %i[create destroy]

  get 'success', to: 'requests#success'

  namespace :admin do

    root 'categories#index'

    resources :categories
    resources :settings, only: %i[index update]
  end

end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  validates_format_of :name, with: /\p{Uppercase_Letter}/, message: 'must start with capital letter'
  validate :category_name

  has_many :posts, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy

  def category_name
    return if self.blank?
    errors.add(Category.name, 'name must be at least 2 words') if name.split.size < 2
    errors.add(Category.name, 'name must end with dot') if name[-1] != '.'
    name.split.each do |word|
      size = word.chars.size
      errors.add(Category.name, 'name must be at least 2 characters each word') if size < 2
    end
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::ApplicationController
  before_action :set_category, only: %i[edit update destroy]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_categories_path, notice: "#{@category.name} has been added"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      redirect_to admin_categories_path, notice: "#{@category.name} has been updated successfully"
    else
      render :edit
    end
  end

  def destroy
    if @category.destroy
      redirect_to admin_categories_path, notice: "#{@category.name} has been removed"
    else
      redirect_to admin_categories_path, alert: "Couldn't remove #{@category.name}"
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to admin_categories_path, alert: 'Category not found'
  end

  def category_params
    params.require(:category).permit(:name, :description)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id]) rescue nil
    if @category.blank?
      redirect_to root_path, alert: 'Category not found'
    else
      @posts = @category.posts.paginate(page: params[:page], per_page: 10).includes(:comments).order('posts.created_at DESC')
      @comment = @category.comments.new
      @comments = @category.comments
    end
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_form.html.erb
<%= render partial: 'layouts/partials/form_error_messages', locals: { object: @category } %>

<p class="label"><%=f.label :name, "Category Name:" %></p>
<p><%=f.text_field :name %></p>

<p class="label"><%=f.label :description, "Description:" %></p>
<p><%=f.text_field :description %></p>

app/views/admin/categories/edit.html.erb
<div class="edit-form">
  <div class="container">
    <div class="page-header">
      <div class="getback">&larr; <%=link_to 'Categories', admin_categories_path %></div>
      <h1>Edit <%=@category.name %></h1>
    </div>
    <div class="row">
      <div class="col-xs-12 .col-sm-6 .col-md-8">
        <%=form_for @category, url: admin_category_path(@category), html: { multipart: true } do |f| %>
          <%= render partial: 'form', locals: { f: f } %>
          <p class="submit"><%=f.submit 'Update Category' %></p>
        <% end %>
      </div>
    </div>
</div>

app/views/admin/categories/index.html.erb
<div class="categories-box">
  <div class="wrapper">  
    <div class="head">
      <p class="move-back">&larr;<%=link_to 'Home Page', root_path %></p>
      <h2 class="box-name">Categories</h2>
      <p class="add btn btn-info"><%=link_to 'Add Category', new_admin_category_path %></p>
    </div>

    <% if @categories.present? %>
      <table class="styled">
        <thead>
          <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
        <% @categories.each do |category| %>
          <tr>
            <td><%=link_to category.name, category_path(category)%></td>
            <td><%=category.description%></td>
            <td><%=link_to "edit", edit_admin_category_path(category)%> / <%=link_to "delete", admin_category_path(category), method: :delete, data: { confirm: "Do you want to delete #{category.name}?" }%></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    <% else %>
      <p class="nothing">There are no Categories yet</p>
    <% end %>

  </div>
</div>

app/views/admin/categories/new.html.erb
<div class="category-form">
  <div class="wrapper">
    
    <h1>Add New Category</h1>

    <div class="add-form">
      <%=form_for @category, url: admin_categories_path do |f| %>
        <%= render partial: 'form', locals: { f: f } %>
        <p class="submit"><%=f.submit 'Add new Category' %></p>
      <% end %>
    </div>
  </div>
</div>