config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get 'login', to: 'home#login'
  get 'logout', to: 'home#logout'
  post 'session', to: 'home#create_session'

  resources :categories, only: :show do
    resources :posts, except: :index
  end

  resources :categories, :posts do
    resources :comments, only: %i[create destroy]
  end

  resources :comments, only: %i[create destroy]

  get 'success', to: 'requests#success'

  namespace :admin do

    root 'categories#index'

    resources :categories
    resources :settings, only: %i[index update]
  end

end

app/models/post.rb
class Post < ApplicationRecord
  has_attached_file :file

  validates :name, presence: true
  validates_format_of :name, with: /\p{Uppercase_Letter}/, message: 'must start with capital letter'
  do_not_validate_attachment_file_type :file
  validates_attachment :file, size: { in: 0..2.megabytes, message: 'File must be smaller than 2Mb' }
  validate :post_name

  belongs_to :category
  has_many :comments, as: :commentable, dependent: :destroy
  #has_many :post_files, dependent: :destroy

  def post_name
    return if self.blank?
    errors.add(Post.name, 'name must be at least 2 words') if name.split.size < 2
    errors.add(Post.name, 'name must end with dot') if name[-1] != '.'
    name.split.each do |word|
      size = word.chars.size
      errors.add(Post.name, 'name must be at least 2 characters each word') if size < 2
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_category
  before_action :set_post, only: %i[edit update destroy show]
  before_action :check_access, only: :destroy

  def show
    @comment = @post.comments.new
    @comments = @post.comments
  end

  def new
    @post = @category.posts.new
  end

  def create
    @post = @category.posts.new(post_params)
    if @post.save
      # if params[:post_files].present?
      #   params[:post_files].each do |file|
      #     PostFile.create(file: file, post_id: @post.id)
      #   end
      # end
      redirect_to category_path(@category), notice: "#{@post.name} has been added"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to category_path(@category), notice: "#{@post.name} has been updated successfully"
    else
      render :edit
    end
  end

  def destroy
    if @post.destroy
      redirect_to category_path(@category), notice: "#{@post.name} has been removed"
    else
      redirect_to category_path(@category), alert: "Couldn't remove #{@post.name}"
    end
  end

  private

  def set_post
    @post = @category.posts.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to category_path(@category), alert: "Couldn't find this post"
  end

  def set_category
    @category = Category.find(params[:category_id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path, alert: 'Category not found'
  end

  def check_access
    redirect_to root_path unless session[:admin] == 'true'
  end

  def post_params
    params.require(:post).permit(:name, :content, :category_id, :file)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="container">
  <%= render partial: 'layouts/partials/form_error_messages', locals: { object: @post } %>

  <div class="centered-wide-form">
    <h3>*Post Title:</h3>
    <p class="label"><%=f.label :name, 'Enter Post Name here:' %></p>
    <p><%=f.text_field :name %></p>

    <h3>*Content:</h3>
    <p class="label"><%=f.label :content, 'Everything You want:' %></p>
    <p><%=f.text_area :content, rows: 6 %></p>

    <h3>File:</h3>
    <p class="label"><%=f.label :file, 'Attach file:' %></p>
    <div class="input-group" style="width: 500px; text-align: center;">
      <span class="input-group-btn">
        <span class="btn btn-small btn-primary btn-inverse" onclick="$(this).parent().find('input[type=file]').click();">Browse</span>
          <%=f.file_field :file, id: nil, autofocus: true, class: "form-control" , onchange: "$(this).parent().parent().find('.form-control').html($(this).val().split(/[\\\\|/]/).pop());", style: "display: none;" %>
      </span>
      <span class="form-control" style="width: 120%;"></span>
    </div>

<!--     <p class="label">Add Files:</p>
    <div class="post-files">
      <div class="input-group" style="width: 500px; text-align: center;">
        <span class="input-group-btn">
          <span class="btn btn-small btn-primary btn-inverse" onclick="$(this).parent().find('input[type=file]').click();">Browse</span>
          <%=f.file_field "post_files[]", id: nil, autofocus: true, class: "form-control" , onchange: "$(this).parent().parent().find('.form-control').html($(this).val().split(/[\\\\|/]/).pop());", style: "display: none;" %>
        </span>
        <span class="form-control" style="width: 120%;"></span>
      </div>
    </div>
    <p><a href="#" id="add-more-files">+ add more files</a></p> -->

    <p class="submit"><%=f.submit 'Send' %></p>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="wrapper">
<div class="container">
  <div class="page-header">
    <h1>Edit <%=@post.name %></h1>
  </div>
  <div class="row">
    <div class="col-xs-12 .col-sm-6 .col-md-8">
      <%=form_for @post, url: category_post_path, html: { multipart: true } do |f| %>
        <%= render partial: 'form', locals: { f: f } %>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/posts/new.html.erb
<div class="post-form">
  <div class="wrapper">
    <div class="page-header"><h1>Add New Post</h1></div>
    <div class="add-form">
      <%=form_for @post, url: category_posts_path, html: { multipart: true } do |f| %>
        <%= render partial: 'form', locals: { f: f } %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="wrapper">
  <div class="move-back">&larr; <%=link_to @category.name, category_path(@category) %></div>
  <div class="container">
    <div class="row">
      <div class="panel panel-default">
        <div class="panel-body">
          <h2><%=@post.name %></h2>
          <p><%=@post.content %></p>
          <p>Attachments:</p>
          <p><%=link_to @post.file.name, @post.file.url(:original, false), target: :_blank %></p>
        </div>
        <div class="panel-body">
          <div class="btn-group" role="group">
            <%= link_to edit_category_post_path(@category, @post), class: 'btn btn-warning btn-sm' do %>
              Edit Post
            <% end %>
            <%= link_to category_post_path(@category, @post), method: :delete, data: { confirm: 'Are you sure you want to delete this post?' }, class: 'btn btn-danger btn-sm' do %>
              Delete Post
            <% end %>
          </div>
        </div>
      </div>				
  	</div>

    <div id="comments">
      <% if @comments.present? %>
        <% @comments.each do |comment| %>
            <% unless comment.new_record? %>
              <%=render partial: 'comments/comment', locals: {comment: comment} %>
            <% end %>
        <% end %>
      <% else %>
        <p>There are no comments here yet in <%=@post.name %></p>
      <% end %>
    </div>

    <div class="comments-form">
      <ul class="errors"></ul>
      <h1>Add New Comment</h1>
      <%=form_for @comment, remote: true, url: post_comments_path(@post) do |f| %>
        <%= render partial: 'comments/form', locals: { f: f } %>
        <p class="submit"><%=f.submit 'Add new Comment' %></p>
      <% end %>
    </div>
 
  </div>
</div>