config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get 'login', to: 'home#login'
  get 'logout', to: 'home#logout'
  post 'session', to: 'home#create_session'

  resources :categories, only: :show do
    resources :posts, except: :index
  end

  resources :categories, :posts do
    resources :comments, only: %i[create destroy]
  end

  resources :comments, only: %i[create destroy]

  get 'success', to: 'requests#success'

  namespace :admin do

    root 'categories#index'

    resources :categories
    resources :settings, only: %i[index update]
  end

end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  validates_format_of :name, with: /\p{Uppercase_Letter}/, message: 'must start with capital letter'
  validate :category_name

  has_many :posts, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy

  def category_name
    return if self.blank?
    errors.add(Category.name, 'name must be at least 2 words') if name.split.size < 2
    errors.add(Category.name, 'name must end with dot') if name[-1] != '.'
    name.split.each do |word|
      size = word.chars.size
      errors.add(Category.name, 'name must be at least 2 characters each word') if size < 2
    end
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::ApplicationController
  before_action :set_category, only: %i[edit update destroy]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_categories_path, notice: "#{@category.name} has been added"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      redirect_to admin_categories_path, notice: "#{@category.name} has been updated successfully"
    else
      render :edit
    end
  end

  def destroy
    if @category.destroy
      redirect_to admin_categories_path, notice: "#{@category.name} has been removed"
    else
      redirect_to admin_categories_path, alert: "Couldn't remove #{@category.name}"
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to admin_categories_path, alert: 'Category not found'
  end

  def category_params
    params.require(:category).permit(:name, :description)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id]) rescue nil
    if @category.blank?
      redirect_to root_path, alert: 'Category not found'
    else
      @posts = @category.posts.paginate(page: params[:page], per_page: 10).includes(:comments).order('posts.created_at DESC')
      @comment = @category.comments.new
      @comments = @category.comments
    end
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/show.html.erb
<div class="category-box">
  <div class="wrapper">
    
    <div class="head">
      <p class="move-back">&larr;<%=link_to 'Categories', root_path %></p>
      <p class="label label-success">Category: <%=@category.name %></p>
      <p class="label label-default">Description: <%=@category.description %></p>
      <p class="badge">Posts: <%=@category.posts.count %></p>
    </div>

    <p class="add btn btn-info"><%=link_to 'Add Post', new_category_post_path(@category) %></p>

    <% if @posts.present? %>
      <% @posts.each do |post| %>
        <div class="panel panel-info">
          <div class="panel-heading">      
            <h3 class="panel-title"><%=link_to post.name, category_post_path(@category, post) %></h3>
          </div>
          <div class="panel-body">
            <h3 class="desc"><%=post.content %></h3>
          </div>
        </div>
      <% end %>     
    <% else %>
      <p class="nothing">There are no Posts here yet in <%=@category.name%></p>
    <% end %>

    <span class="pagination"><%= will_paginate @posts %></span>

    <div id="comments">
      <% if @comments.present? %>
        <% @comments.each do |comment| %>
            <% unless comment.new_record? %>
              <%=render partial: 'comments/comment', locals: {comment: comment} %>
            <% end %>
        <% end %>
      <% else %>
        <p>There are no comments here yet in <%=@category.name %></p>
      <% end %>
    </div>

    <div class="comments-form">
      <ul class="errors"></ul>
      <h1>Add New Comment</h1>
      <%=form_for @comment, remote: true, url: category_comments_path(@category) do |f| %>
        <%= render partial: 'comments/form', locals: { f: f } %>
        <p class="submit"><%=f.submit 'Add new Comment' %></p>
      <% end %>
    </div>

  </div>
</div>